version: '3.9'
services:
  swarm-api:
    build: .
    environment:
      ENV_ID: prod
      SERVICE_NAME: swarm-api
    ports:
      - 60002:60002
    volumes:
      - ./config/config.live.json:/app/config/config.json
    network_mode: host