#version: '3.9'
services:
  swarm-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    environment:
      ENV_ID: dev
      SERVICE_NAME: swarm-api
    ports:
      - 8100:8100
    volumes:
      - ./:/app
#    network_mode: bridge
#    networks:
#      - gratheon
#networks:
#  gratheon:
