version: '3.9'
services:
  swarm-api:
    build: .
    environment:
      ENV_ID: dev
      SERVICE_NAME: swarm-api
    ports:
      - 8100:8100
    network_mode: bridge
    networks:
      - gratheon
networks:
  gratheon:
