version: '3.9'
services:
  swarm-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    environment:
      ENV_ID: dev
      SERVICE_NAME: swarm-api
    ports:
      - 8100:8100
    volumes:
      - ./:/app
    networks:
      - gratheon_default

networks:
  gratheon_default:
    external: true
