version: '3.9'
services:
  swarm-api:
    build: .
    environment:
      ENV_ID: dev
      SERVICE_NAME: swarm-api
    ports:
      - 60002:60002
    volumes:
      - ./config/config.json:/app/config/config.json
    network_mode: bridge
    networks:
      - gratheon
networks:
  gratheon:
