-- +goose Up
ALTER TABLE `boxes` CHANGE `type` `type`
ENUM(
  'SUPER',
  'DEEP',
  'LARGE_HORIZONTAL_SECTION',
  'GATE',
  'VENTILATION',
  'QUEEN_EXCLUDER',
  'HORIZONTAL_FEEDER',
  'BOTTOM'
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'DEEP';

ALTER TABLE `warehouse_modules`
MODIFY COLUMN `module_type` enum(
  'DEEP',
  'SUPER',
  'LARGE_HORIZONTAL_SECTION',
  'ROOF',
  'HORIZONTAL_FEEDER',
  'QUEEN_EXCLUDER',
  'BOTTOM',
  'FRAME_FOUNDATION',
  'FRAME_EMPTY_COMB',
  'FRAME_PARTITION',
  'FRAME_FEEDER'
) NOT NULL;

-- +goose Down
ALTER TABLE `boxes` CHANGE `type` `type`
ENUM(
  'SUPER',
  'DEEP',
  'GATE',
  'VENTILATION',
  'QUEEN_EXCLUDER',
  'HORIZONTAL_FEEDER',
  'BOTTOM'
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'DEEP';

ALTER TABLE `warehouse_modules`
MODIFY COLUMN `module_type` enum(
  'DEEP',
  'SUPER',
  'ROOF',
  'HORIZONTAL_FEEDER',
  'QUEEN_EXCLUDER',
  'BOTTOM',
  'FRAME_FOUNDATION',
  'FRAME_EMPTY_COMB',
  'FRAME_PARTITION',
  'FRAME_FEEDER'
) NOT NULL;
