package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/Gratheon/swarm-api/graph/generated"
	"github.com/Gratheon/swarm-api/graph/model"
)

// FindFrameSideByID is the resolver for the findFrameSideByID field.
func (r *entityResolver) FindFrameSideByID(ctx context.Context, id *string) (*model.FrameSide, error) {
	panic(fmt.Errorf("not implemented"))
}

// FindHiveByID is the resolver for the findHiveByID field.
func (r *entityResolver) FindHiveByID(ctx context.Context, id string) (*model.Hive, error) {
	panic(fmt.Errorf("not implemented"))
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
