package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"errors"
	"math/rand"
	"strconv"
	"time"

	"github.com/Gratheon/swarm-api/graph/generated"
	"github.com/Gratheon/swarm-api/graph/model"
	"github.com/Gratheon/swarm-api/logger"
	"github.com/Gratheon/swarm-api/redisPubSub"
)

// Hives is the resolver for the hives field.
func (r *apiaryResolver) Hives(ctx context.Context, obj *model.Apiary) ([]*model.Hive, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).ListByApiary(obj.ID)
}

// Frames is the resolver for the frames field.
func (r *boxResolver) Frames(ctx context.Context, obj *model.Box) ([]*model.Frame, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Frame{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).ListByBox(obj.ID)
}

// LastTreatment is the resolver for the lastTreatment field.
func (r *familyResolver) LastTreatment(ctx context.Context, obj *model.Family) (*string, error) {
	uid := ctx.Value("userID").(string)
	treatmentModel := &model.Treatment{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	treatment, err := treatmentModel.GetLastFamilyTreatment(obj.ID)
	if err != nil {
		return nil, err
	}

	if treatment == nil {
		return nil, nil
	}

	return &treatment.Added, nil
}

// Treatments is the resolver for the treatments field.
func (r *familyResolver) Treatments(ctx context.Context, obj *model.Family) ([]*model.Treatment, error) {
	uid := ctx.Value("userID").(string)
	treatmentModel := &model.Treatment{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	return treatmentModel.ListFamilyTreatments(obj.ID)
}

// LeftSide is the resolver for the leftSide field.
func (r *frameResolver) LeftSide(ctx context.Context, obj *model.Frame) (*model.FrameSide, error) {
	uid := ctx.Value("userID").(string)
	return (&model.FrameSide{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Get(obj.LeftID)
}

// RightSide is the resolver for the rightSide field.
func (r *frameResolver) RightSide(ctx context.Context, obj *model.Frame) (*model.FrameSide, error) {
	uid := ctx.Value("userID").(string)
	return (&model.FrameSide{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Get(obj.RightID)
}

// Boxes is the resolver for the boxes field.
func (r *hiveResolver) Boxes(ctx context.Context, obj *model.Hive) ([]*model.Box, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Box{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).ListByHive(obj.ID)
}

// Family is the resolver for the family field.
func (r *hiveResolver) Family(ctx context.Context, obj *model.Hive) (*model.Family, error) {
	uid := ctx.Value("userID").(string)
	if obj.FamilyID == nil {
		return nil, nil
	}

	return (&model.Family{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).GetById(obj.FamilyID)
}

// BoxCount is the resolver for the boxCount field.
func (r *hiveResolver) BoxCount(ctx context.Context, obj *model.Hive) (int, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Box{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Count(obj.ID)
}

// InspectionCount is the resolver for the inspectionCount field.
func (r *hiveResolver) InspectionCount(ctx context.Context, obj *model.Hive) (int, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Inspection{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).CountByHiveId(obj.ID)
}

// IsNew is the resolver for the isNew field.
func (r *hiveResolver) IsNew(ctx context.Context, obj *model.Hive) (bool, error) {
	if obj.Added == nil {
		return false, nil
	}
	// return true if obj.Added is less than 1 day old
	now := time.Now()
	added, err := time.Parse(time.DateTime, *obj.Added)

	if err != nil {
		return false, err
	}

	return now.Sub(added).Hours() < 24, nil
}

// LastInspection is the resolver for the lastInspection field.
func (r *hiveResolver) LastInspection(ctx context.Context, obj *model.Hive) (*string, error) {
	uid := ctx.Value("userID").(string)
	inspectionModel := &model.Inspection{
		Db:     r.Resolver.Db,
		UserID: uid,
	}
	inspection, err := inspectionModel.GetLatestByHiveId(obj.ID)
	if err != nil {
		return nil, err
	}

	if inspection == nil {
		return nil, nil
	}

	return &inspection.Added, nil
}

// ParentHive is the resolver for the parentHive field.
func (r *hiveResolver) ParentHive(ctx context.Context, obj *model.Hive) (*model.Hive, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).GetParentHive(obj.ParentHiveID)
}

// ChildHives is the resolver for the childHives field.
func (r *hiveResolver) ChildHives(ctx context.Context, obj *model.Hive) ([]*model.Hive, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).GetChildHives(obj.ID)
}

// MergedIntoHive is the resolver for the mergedIntoHive field.
func (r *hiveResolver) MergedIntoHive(ctx context.Context, obj *model.Hive) (*model.Hive, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).GetMergedIntoHive(obj.MergedIntoHiveID)
}

// MergedFromHives is the resolver for the mergedFromHives field.
func (r *hiveResolver) MergedFromHives(ctx context.Context, obj *model.Hive) ([]*model.Hive, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).GetMergedFromHives(obj.ID)
}

// AddApiary is the resolver for the addApiary field.
func (r *mutationResolver) AddApiary(ctx context.Context, apiary model.ApiaryInput) (*model.Apiary, error) {
	uid := ctx.Value("userID").(string)
	createdApiary, err := (&model.Apiary{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Create(apiary)

	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}

	redisPubSub.PublishEvent(uid, "apiary", strconv.Itoa(createdApiary.ID), "created", createdApiary)

	return createdApiary, err
}

// UpdateApiary is the resolver for the updateApiary field.
func (r *mutationResolver) UpdateApiary(ctx context.Context, id string, apiary model.ApiaryInput) (*model.Apiary, error) {
	uid := ctx.Value("userID").(string)
	updatedApiary, err := (&model.Apiary{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Update(id, apiary)

	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}

	redisPubSub.PublishEvent(uid, "apiary", id, "updated", updatedApiary)

	return updatedApiary, err
}

// DeactivateApiary is the resolver for the deactivateApiary field.
func (r *mutationResolver) DeactivateApiary(ctx context.Context, id string) (*bool, error) {
	uid := ctx.Value("userID").(string)
	result, err := (&model.Apiary{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Deactivate(id)

	redisPubSub.PublishEvent(uid, "apiary", id, "deleted", "")
	return result, err
}

// AddHive is the resolver for the addHive field.
func (r *mutationResolver) AddHive(ctx context.Context, hive model.HiveInput) (*model.Hive, error) {
	uid := ctx.Value("userID").(string)

	race := "unknown"
	// generate current year
	year := time.Now().Year()
	added := strconv.Itoa(year)

	FamilyID, err := (&model.Family{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Create(&race, &added)

	if err != nil {
		logger.Error(err.Error())
	}

	hiveResult, err := (&model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Create(hive, FamilyID)

	if err != nil {
		logger.Error(err.Error())
	}

	err = (&model.Box{
		Db:     r.Db,
		UserID: uid,
	}).CreateByHiveId(hiveResult.ID, hive.BoxCount, hive.Colors)

	if err != nil {
		logger.Error(err.Error())
	}

	boxes, err := (&model.Box{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).ListByHive(hiveResult.ID)

	if err == nil {
		for _, box := range boxes {
			err = (&model.Frame{
				Db:     r.Db,
				UserID: uid,
			}).CreateFramesForBox(box.ID, hive.FrameCount)
		}
	}

	if err != nil {
		logger.Error(err.Error())
	}

	return hiveResult, err
}

// UpdateHive is the resolver for the updateHive field.
func (r *mutationResolver) UpdateHive(ctx context.Context, hive model.HiveUpdateInput) (*model.Hive, error) {
	uid := ctx.Value("userID").(string)

	hiveModel := &model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	familyModel := &model.Family{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	familyID, err := familyModel.Upsert(uid, hive)
	if err != nil {
		logger.Error(err.Error())
	}

	err = hiveModel.Update(hive.ID, hive.Name, hive.Notes, familyID)

	if err != nil {
		logger.Error(err.Error())
	}

	return hiveModel.Get(hive.ID)
}

// DeactivateHive is the resolver for the deactivateHive field.
func (r *mutationResolver) DeactivateHive(ctx context.Context, id string) (*bool, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Deactivate(id)
}

// AddBox is the resolver for the addBox field.
func (r *mutationResolver) AddBox(ctx context.Context, hiveID string, position int, color *string, typeArg model.BoxType) (*model.Box, error) {
	uid := ctx.Value("userID").(string)

	boxModel := &model.Box{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	boxID, err := boxModel.Create(hiveID, position, color, typeArg)

	if err != nil {
		logger.Error(err.Error())
	}

	return boxModel.Get(*boxID)
}

// UpdateBoxColor is the resolver for the updateBoxColor field.
func (r *mutationResolver) UpdateBoxColor(ctx context.Context, id string, color *string) (bool, error) {
	uid := ctx.Value("userID").(string)
	boxModel := &model.Box{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	box, err := boxModel.Get(id)

	if err != nil {
		logger.Error(err.Error())
	}

	box.Color = color

	return boxModel.Update(box.ID, *box.Position, box.Color)
}

// DeactivateBox is the resolver for the deactivateBox field.
func (r *mutationResolver) DeactivateBox(ctx context.Context, id string) (*bool, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Box{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Deactivate(id)
}

// SwapBoxPositions is the resolver for the swapBoxPositions field.
func (r *mutationResolver) SwapBoxPositions(ctx context.Context, id string, id2 string) (*bool, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Box{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).SwapBoxPositions(id, id2)
}

// AddFrame is the resolver for the addFrame field.
func (r *mutationResolver) AddFrame(ctx context.Context, boxID string, typeArg string, position int) (*model.Frame, error) {
	uid := ctx.Value("userID").(string)

	frameModel := &model.Frame{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	if frameModel.IsFrameWithSides(model.FrameType(typeArg)) {
		leftSide := &model.FrameSide{
			Db:     r.Resolver.Db,
			UserID: uid,
		}
		rightSide := &model.FrameSide{
			Db:     r.Resolver.Db,
			UserID: uid,
		}

		leftID, err := leftSide.CreateSide(leftSide)

		if err != nil {
			return nil, err
		}

		rightID, err := rightSide.CreateSide(rightSide)

		if err != nil {
			return nil, err
		}

		frameId, err := frameModel.Create(&boxID, position, model.FrameType(typeArg), leftID, rightID)

		if err != nil {
			logger.Error(err.Error())
			return nil, err
		}

		return frameModel.Get(*frameId)

	} else {
		frameId, err := frameModel.Create(&boxID, position, model.FrameType(typeArg), nil, nil)

		if err != nil {
			logger.Error(err.Error())
		}

		return frameModel.Get(*frameId)
	}
}

// UpdateFrames is the resolver for the updateFrames field.
func (r *mutationResolver) UpdateFrames(ctx context.Context, frames []*model.FrameInput) ([]*model.Frame, error) {
	uid := ctx.Value("userID").(string)
	frameModel := &model.Frame{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	// Initialize an empty results slice
	results := []*model.Frame{}

	for _, frame := range frames {
		frameModel.Update(frame.ID, frame.BoxID, frame.Position)
		id, err := strconv.ParseInt(frame.ID, 10, 64)
		if err != nil {
			return nil, err
		}

		updatedFrame, err := frameModel.Get(id)
		if err != nil {
			return nil, err
		}

		results = append(results, updatedFrame)
	}

	return results, nil
}

// DeactivateFrame is the resolver for the deactivateFrame field.
func (r *mutationResolver) DeactivateFrame(ctx context.Context, id string) (*bool, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Frame{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Deactivate(id)
}

// AddInspection is the resolver for the addInspection field.
func (r *mutationResolver) AddInspection(ctx context.Context, inspection model.InspectionInput) (*model.Inspection, error) {
	uid := ctx.Value("userID").(string)
	inspectionModel := &model.Inspection{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	id, err := inspectionModel.Create(inspection.Data, inspection.HiveID)
	if err != nil {
		return nil, err
	}

	return inspectionModel.Get(*id)
}

// TreatHive is the resolver for the treatHive field.
func (r *mutationResolver) TreatHive(ctx context.Context, treatment model.TreatmentOfHiveInput) (*bool, error) {
	uid := ctx.Value("userID").(string)
	treatmentModel := &model.Treatment{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	hiveModel := &model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	hive, err := hiveModel.Get(treatment.HiveID)
	if err != nil {
		logger.Error(err.Error())
		ok := err == nil
		return &ok, err
	}

	_, err2 := treatmentModel.TreatHive(treatment, hive.FamilyID)
	ok := err2 == nil

	if err2 != nil {
		logger.Error(err2.Error())
	}

	return &ok, err
}

// TreatBox is the resolver for the treatBox field.
func (r *mutationResolver) TreatBox(ctx context.Context, treatment model.TreatmentOfBoxInput) (*bool, error) {
	uid := ctx.Value("userID").(string)
	treatmentModel := &model.Treatment{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	hiveModel := &model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	hive, err := hiveModel.Get(treatment.HiveID)
	if err != nil {
		logger.Error(err.Error())
		ok := err == nil
		return &ok, err
	}

	_, err2 := treatmentModel.TreatHiveBox(treatment, hive.FamilyID)
	ok := err2 == nil
	if err2 != nil {
		logger.Error(err2.Error())
	}
	return &ok, err
}

// MarkHiveAsCollapsed is the resolver for the markHiveAsCollapsed field.
func (r *mutationResolver) MarkHiveAsCollapsed(ctx context.Context, id string, collapseDate string, collapseCause string) (*model.Hive, error) {
	uid := ctx.Value("userID").(string)
	hiveModel := &model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	parsedCollapseDate, err := time.Parse(time.RFC3339, collapseDate)
	if err != nil {
		parsedCollapseDate, err = time.Parse("2006-01-02", collapseDate)
		if err != nil {
			logger.Error("Invalid collapseDate format: " + err.Error())
			return nil, errors.New("Invalid collapseDate format, must be RFC3339 or YYYY-MM-DD")
		}
	}

	err = hiveModel.MarkAsCollapsed(id, parsedCollapseDate, collapseCause)
	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}

	updatedHive, err := hiveModel.Get(id)
	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}

	return updatedHive, nil
}

// SplitHive is the resolver for the splitHive field.
func (r *mutationResolver) SplitHive(ctx context.Context, sourceHiveID string, name string, frameIds []string) (*model.Hive, error) {
	uid := ctx.Value("userID").(string)

	if len(frameIds) == 0 || len(frameIds) > 10 {
		return nil, errors.New("must select between 1 and 10 frames to split")
	}

	hiveModel := &model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	sourceHive, err := hiveModel.Get(sourceHiveID)
	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}
	if sourceHive == nil {
		return nil, errors.New("source hive not found")
	}

	newHive, err := hiveModel.Split(sourceHiveID, name, sourceHive.ApiaryID, sourceHive.FamilyID)
	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}

	boxModel := &model.Box{
		Db:     r.Db,
		UserID: uid,
	}

	newBoxID, err := boxModel.CreateSingleBox(newHive.ID, 0, "#ffc848", model.BoxTypeDeep)
	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}

	frameModel := &model.Frame{
		Db:     r.Db,
		UserID: uid,
	}

	err = frameModel.MoveFramesToBox(frameIds, newBoxID)
	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}

	redisPubSub.PublishEvent(uid, "hive", newHive.ID, "split", newHive)

	return newHive, nil
}

// JoinHives is the resolver for the joinHives field.
func (r *mutationResolver) JoinHives(ctx context.Context, sourceHiveID string, targetHiveID string, mergeType string) (*model.Hive, error) {
	uid := ctx.Value("userID").(string)

	validMergeTypes := map[string]bool{
		"both_queens":       true,
		"source_queen_kept": true,
		"target_queen_kept": true,
	}
	if !validMergeTypes[mergeType] {
		return nil, errors.New("invalid merge type")
	}

	hiveModel := &model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	sourceHive, err := hiveModel.Get(sourceHiveID)
	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}
	if sourceHive == nil {
		return nil, errors.New("source hive not found")
	}

	targetHive, err := hiveModel.Get(targetHiveID)
	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}
	if targetHive == nil {
		return nil, errors.New("target hive not found")
	}

	boxModel := &model.Box{
		Db:     r.Db,
		UserID: uid,
	}

	sourceBoxes, err := boxModel.ListByHive(sourceHiveID)
	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}

	boxesToKeepInSource, err := boxModel.GetBoxesByTypeForHive(sourceHiveID, []model.BoxType{model.BoxTypeBottom, model.BoxTypeGate})
	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}

	keepInSourceMap := make(map[string]bool)
	for _, box := range boxesToKeepInSource {
		if box.ID != nil {
			keepInSourceMap[*box.ID] = true
		}
	}

	var boxIDsToMove []string
	for _, box := range sourceBoxes {
		if box.ID != nil && !keepInSourceMap[*box.ID] {
			boxIDsToMove = append(boxIDsToMove, *box.ID)
		}
	}

	if len(boxIDsToMove) > 0 {
		maxPos, err := boxModel.GetMaxPosition(targetHiveID)
		if err != nil {
			logger.Error(err.Error())
			return nil, err
		}

		err = boxModel.MoveBoxesToHive(boxIDsToMove, targetHiveID, maxPos+1)
		if err != nil {
			logger.Error(err.Error())
			return nil, err
		}
	}

	now := time.Now()
	err = hiveModel.MarkAsMerged(sourceHiveID, targetHiveID, now, mergeType)
	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}

	updatedTargetHive, err := hiveModel.Get(targetHiveID)
	if err != nil {
		logger.Error(err.Error())
		return nil, err
	}

	redisPubSub.PublishEvent(uid, "hive", targetHiveID, "join", updatedTargetHive)
	redisPubSub.PublishEvent(uid, "hive", sourceHiveID, "merged", sourceHive)

	return updatedTargetHive, nil
}

// Hive is the resolver for the hive field.
func (r *queryResolver) Hive(ctx context.Context, id string) (*model.Hive, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Get(id)
}

// Apiary is the resolver for the apiary field.
func (r *queryResolver) Apiary(ctx context.Context, id string) (*model.Apiary, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Apiary{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Get(id)
}

// HiveFrame is the resolver for the hiveFrame field.
func (r *queryResolver) HiveFrame(ctx context.Context, id string) (*model.Frame, error) {
	uid := ctx.Value("userID").(string)
	idNum, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}
	return (&model.Frame{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Get(idNum)
}

// HiveFrameSide is the resolver for the hiveFrameSide field.
func (r *queryResolver) HiveFrameSide(ctx context.Context, id string) (*model.FrameSide, error) {
	uid := ctx.Value("userID").(string)
	idNum, err := strconv.ParseInt(id, 10, 64)

	if err != nil {
		return nil, err
	}
	idNum2 := int(idNum)

	return (&model.FrameSide{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Get(&idNum2)
}

// Apiaries is the resolver for the apiaries field.
func (r *queryResolver) Apiaries(ctx context.Context) ([]*model.Apiary, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Apiary{
		Db:     r.Db,
		UserID: uid,
	}).List()
}

// Inspection is the resolver for the inspection field.
func (r *queryResolver) Inspection(ctx context.Context, inspectionID string) (*model.Inspection, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Inspection{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Get(inspectionID)
}

// RandomHiveName is the resolver for the randomHiveName field.
func (r *queryResolver) RandomHiveName(ctx context.Context, language *string) (*string, error) {
	langCode := "en" // Default to English
	if language != nil {
		langCode = *language
	}

	// Access the map from the resolver
	names, ok := r.Resolver.femaleNamesMap[langCode]
	if !ok || len(names) == 0 {
		// Fallback to English if the requested language is not found or empty
		names, ok = r.Resolver.femaleNamesMap["en"]
		if !ok || len(names) == 0 {
			// Should not happen if en names exist in the json
			logger.Error(errors.New("fallback to 'en' names failed or 'en' list is empty").Error()) // Log specific error
			defaultName := "Bee"                                                                    // Provide a fallback name
			return &defaultName, nil
		}
	}

	// Select a random name from the chosen list
	randomIndex := rand.Intn(len(names))
	randomName := names[randomIndex]

	return &randomName, nil
}

// Inspections is the resolver for the inspections field.
func (r *queryResolver) Inspections(ctx context.Context, hiveID string, limit *int) ([]*model.Inspection, error) {
	uid := ctx.Value("userID").(string)
	return (&model.Inspection{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).ListByHiveId(hiveID)
}

// Apiary returns generated.ApiaryResolver implementation.
func (r *Resolver) Apiary() generated.ApiaryResolver { return &apiaryResolver{r} }

// Box returns generated.BoxResolver implementation.
func (r *Resolver) Box() generated.BoxResolver { return &boxResolver{r} }

// Family returns generated.FamilyResolver implementation.
func (r *Resolver) Family() generated.FamilyResolver { return &familyResolver{r} }

// Frame returns generated.FrameResolver implementation.
func (r *Resolver) Frame() generated.FrameResolver { return &frameResolver{r} }

// Hive returns generated.HiveResolver implementation.
func (r *Resolver) Hive() generated.HiveResolver { return &hiveResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type apiaryResolver struct{ *Resolver }
type boxResolver struct{ *Resolver }
type familyResolver struct{ *Resolver }
type frameResolver struct{ *Resolver }
type hiveResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
