package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"strconv"

	"github.com/Gratheon/swarm-api/graph/generated"
	"github.com/Gratheon/swarm-api/graph/model"
)

// Hives is the resolver for the hives field.
func (r *apiaryResolver) Hives(ctx context.Context, obj *model.Apiary, sortBy *model.HiveSortBy, sortOrder *model.SortOrder) ([]*model.Hive, error) {
	uid := ctx.Value("userID").(string)
	if sortBy != nil || sortOrder != nil {
		effectiveSortBy := model.HiveSortByHiveNumber
		if sortBy != nil {
			effectiveSortBy = *sortBy
		}

		effectiveSortOrder := model.SortOrderAsc
		if sortOrder != nil {
			effectiveSortOrder = *sortOrder
		}

		return (&model.Hive{
			Db:     r.Resolver.Db,
			UserID: uid,
		}).ListByApiarySorted(obj.ID, effectiveSortBy, effectiveSortOrder)
	}

	loaders := GetLoaders(ctx)
	if loaders != nil && loaders.HivesByApiaryLoader != nil {
		return loaders.HivesByApiaryLoader.Load(ctx, obj.ID, uid)
	}
	return (&model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).ListByApiary(obj.ID)
}

// Type is the resolver for the type field.
func (r *apiaryObstacleResolver) Type(ctx context.Context, obj *model.ApiaryObstacle) (model.ObstacleType, error) {
	return model.ObstacleType(obj.Type), nil
}

// Frames is the resolver for the frames field.
func (r *boxResolver) Frames(ctx context.Context, obj *model.Box) ([]*model.Frame, error) {
	uid := ctx.Value("userID").(string)
	loaders := GetLoaders(ctx)
	if loaders != nil && loaders.FramesByBoxLoader != nil {
		return loaders.FramesByBoxLoader.Load(ctx, *obj.ID, uid)
	}
	return (&model.Frame{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).ListByBox(obj.ID)
}

// LastTreatment is the resolver for the lastTreatment field.
func (r *familyResolver) LastTreatment(ctx context.Context, obj *model.Family) (*string, error) {
	uid := ctx.Value("userID").(string)
	treatmentModel := &model.Treatment{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	treatment, err := treatmentModel.GetLastFamilyTreatment(obj.ID)
	if err != nil {
		return nil, err
	}

	if treatment == nil {
		return nil, nil
	}

	return &treatment.Added, nil
}

// Treatments is the resolver for the treatments field.
func (r *familyResolver) Treatments(ctx context.Context, obj *model.Family) ([]*model.Treatment, error) {
	uid := ctx.Value("userID").(string)
	treatmentModel := &model.Treatment{
		Db:     r.Resolver.Db,
		UserID: uid,
	}

	return treatmentModel.ListFamilyTreatments(obj.ID)
}

// LastHive is the resolver for the lastHive field.
func (r *familyResolver) LastHive(ctx context.Context, obj *model.Family) (*model.Hive, error) {
	uid := ctx.Value("userID").(string)

	lastHiveID, err := (&model.Family{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).LastHiveID(obj.ID)
	if err != nil {
		return nil, err
	}
	if lastHiveID == nil {
		return nil, nil
	}

	return (&model.Hive{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Get(strconv.Itoa(*lastHiveID))
}

// LeftSide is the resolver for the leftSide field.
func (r *frameResolver) LeftSide(ctx context.Context, obj *model.Frame) (*model.FrameSide, error) {
	uid := ctx.Value("userID").(string)
	loaders := GetLoaders(ctx)
	if loaders != nil && loaders.FrameSideLoader != nil {
		return loaders.FrameSideLoader.Load(ctx, obj.LeftID, uid)
	}
	return (&model.FrameSide{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Get(obj.LeftID)
}

// RightSide is the resolver for the rightSide field.
func (r *frameResolver) RightSide(ctx context.Context, obj *model.Frame) (*model.FrameSide, error) {
	uid := ctx.Value("userID").(string)
	loaders := GetLoaders(ctx)
	if loaders != nil && loaders.FrameSideLoader != nil {
		return loaders.FrameSideLoader.Load(ctx, obj.RightID, uid)
	}
	return (&model.FrameSide{
		Db:     r.Resolver.Db,
		UserID: uid,
	}).Get(obj.RightID)
}

// Apiary returns generated.ApiaryResolver implementation.
func (r *Resolver) Apiary() generated.ApiaryResolver { return &apiaryResolver{r} }

// ApiaryObstacle returns generated.ApiaryObstacleResolver implementation.
func (r *Resolver) ApiaryObstacle() generated.ApiaryObstacleResolver {
	return &apiaryObstacleResolver{r}
}

// Box returns generated.BoxResolver implementation.
func (r *Resolver) Box() generated.BoxResolver { return &boxResolver{r} }

// Family returns generated.FamilyResolver implementation.
func (r *Resolver) Family() generated.FamilyResolver { return &familyResolver{r} }

// Frame returns generated.FrameResolver implementation.
func (r *Resolver) Frame() generated.FrameResolver { return &frameResolver{r} }

// Hive returns generated.HiveResolver implementation.
func (r *Resolver) Hive() generated.HiveResolver { return &hiveResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type apiaryResolver struct{ *Resolver }
type apiaryObstacleResolver struct{ *Resolver }
type boxResolver struct{ *Resolver }
type familyResolver struct{ *Resolver }
type frameResolver struct{ *Resolver }
type hiveResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
