// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// Input for creating or updating an apiary location
type ApiaryInput struct {
	// Display name of the apiary
	Name string `json:"name"`
	// Apiary mode: fixed location or transported mobile setup
	Type *ApiaryType `json:"type,omitempty"`
	// Latitude coordinate as string
	Lat *string `json:"lat,omitempty"`
	// Longitude coordinate as string
	Lng *string `json:"lng,omitempty"`
}

// Input for creating or updating an apiary obstacle
type ApiaryObstacleInput struct {
	// Shape type
	Type ObstacleType `json:"type"`
	// X coordinate
	X float64 `json:"x"`
	// Y coordinate
	Y float64 `json:"y"`
	// Width (for rectangles)
	Width *float64 `json:"width,omitempty"`
	// Height (for rectangles)
	Height *float64 `json:"height,omitempty"`
	// Radius (for circles)
	Radius *float64 `json:"radius,omitempty"`
	// Rotation angle (for rectangles)
	Rotation *float64 `json:"rotation,omitempty"`
	// Optional descriptive label
	Label *string `json:"label,omitempty"`
}

// Input for creating or updating a box in a hive
type BoxInput struct {
	ID *string `json:"id,omitempty"`
	// Position in hive (0=bottom, increases upward)
	Position int `json:"position"`
	// Visual color marker painted on box
	Color *string `json:"color,omitempty"`
	// Type of box (determines height and usage)
	Type BoxType `json:"type"`
	// ignored, added for frontend ease
	HiveID *int         `json:"hiveId,omitempty"`
	Family *FamilyInput `json:"family,omitempty"`
}

type DeviceInput struct {
	// Display name of the device
	Name string `json:"name"`
	// Device type for downstream integrations
	Type DeviceType `json:"type"`
	// API token bound to this device (must be unique when set)
	APIToken *string `json:"apiToken,omitempty"`
	// Optional hive linked to this device
	HiveID *string `json:"hiveId,omitempty"`
	// Optional specific hive section (box) linked to this device
	BoxID *string `json:"boxId,omitempty"`
}

type DeviceUpdateInput struct {
	// Display name of the device
	Name *string `json:"name,omitempty"`
	// Device type for downstream integrations
	Type *DeviceType `json:"type,omitempty"`
	// API token bound to this device (must be unique when set)
	APIToken *string `json:"apiToken,omitempty"`
	// Optional hive linked to this device
	HiveID *string `json:"hiveId,omitempty"`
	// Optional specific hive section (box) linked to this device
	BoxID *string `json:"boxId,omitempty"`
}

// Input for creating or updating a queen family
type FamilyInput struct {
	// Family ID for updates
	ID *string `json:"id,omitempty"`
	// Name of the queen bee
	Name *string `json:"name,omitempty"`
	// Bee race/breed (e.g., 'Carniolan', 'Italian', 'Buckfast')
	Race *string `json:"race,omitempty"`
	// Year when queen was introduced
	Added *string `json:"added,omitempty"`
	// Custom queen marking color (overrides standard year-based color)
	Color *string `json:"color,omitempty"`
}

// Input for updating frame properties
type FrameInput struct {
	ID string `json:"id"`
	// Position within box (0-based index)
	Position int `json:"position"`
	// Frame content type
	Type FrameType `json:"type"`
	// ignored, added for frontend ease
	BoxID string `json:"boxId"`
	// ignored, added for frontend ease
	HiveID *int `json:"hiveId,omitempty"`
}

// Input for creating a new hive with initial configuration
type HiveInput struct {
	// Parent apiary location ID
	ApiaryID string `json:"apiaryId"`
	// Optional custom name for the queen (bee family)
	QueenName *string `json:"queenName,omitempty"`
	// Year the queen was introduced (defaults to current year)
	QueenYear *string `json:"queenYear,omitempty"`
	// Custom queen marking color (overrides year-based marking)
	QueenColor *string `json:"queenColor,omitempty"`
	// Optional identifier number for this hive
	HiveNumber *int `json:"hiveNumber,omitempty"`
	// Number of boxes to create (e.g., 2 for deep+super)
	BoxCount int `json:"boxCount"`
	// Number of frames per box
	FrameCount int `json:"frameCount"`
	// Initial section type used for first created boxes
	InitialBoxType *BoxType `json:"initialBoxType,omitempty"`
	// Selected box system for this hive (defaults to Langstroth)
	BoxSystemID *string `json:"boxSystemId,omitempty"`
	// Color markers for each box
	Colors []*string `json:"colors,omitempty"`
}

type HiveLogInput struct {
	HiveID       string                     `json:"hiveId"`
	Action       string                     `json:"action"`
	Title        string                     `json:"title"`
	Details      *string                    `json:"details,omitempty"`
	Source       *string                    `json:"source,omitempty"`
	DedupeKey    *string                    `json:"dedupeKey,omitempty"`
	RelatedHives []*HiveLogRelatedHiveInput `json:"relatedHives,omitempty"`
}

type HiveLogRelatedHive struct {
	ID         string `json:"id"`
	HiveNumber *int   `json:"hiveNumber,omitempty"`
}

type HiveLogRelatedHiveInput struct {
	ID         string `json:"id"`
	HiveNumber *int   `json:"hiveNumber,omitempty"`
}

type HiveLogUpdateInput struct {
	Title        *string                    `json:"title,omitempty"`
	Details      *string                    `json:"details,omitempty"`
	RelatedHives []*HiveLogRelatedHiveInput `json:"relatedHives,omitempty"`
}

// Input for updating existing hive details
type HiveUpdateInput struct {
	ID string `json:"id"`
	// Hive identifier number visible to beekeeper
	HiveNumber *int `json:"hiveNumber,omitempty"`
	// Free-form notes about the hive
	Notes *string `json:"notes,omitempty"`
	// Update queen/family information
	Family *FamilyInput `json:"family,omitempty"`
}

type InspectionInput struct {
	HiveID int    `json:"hiveId"`
	Data   string `json:"data"`
}

// The mutation type, represents all updates we can make to our data
type Mutation struct {
}

// The query type, represents all of the entry points into our object graph
type Query struct {
}

// Input for treating a specific box with anti-varroa medication
type TreatmentOfBoxInput struct {
	HiveID string `json:"hiveId"`
	BoxID  string `json:"boxId"`
	// Type of treatment (e.g., 'oxalic_acid', 'formic_acid', 'amitraz')
	Type string `json:"type"`
}

// Input for treating entire hive with anti-varroa medication
type TreatmentOfHiveInput struct {
	HiveID string `json:"hiveId"`
	// Type of treatment (e.g., 'oxalic_acid', 'formic_acid', 'amitraz')
	Type string `json:"type"`
}

// Box types with different heights and purposes
type BoxType string

const (
	// Deep box for brood (10 frames, 9-5/8" tall)
	BoxTypeDeep BoxType = "DEEP"
	// Shallow box for honey (10 frames, 5-11/16" tall)
	BoxTypeSuper BoxType = "SUPER"
	// Protective top cover of the hive
	BoxTypeRoof BoxType = "ROOF"
	// Long horizontal section with large frame capacity
	BoxTypeLargeHorizontalSection BoxType = "LARGE_HORIZONTAL_SECTION"
	// Entrance management/reducer gate
	BoxTypeGate BoxType = "GATE"
	// Ventilation screen for airflow
	BoxTypeVentilation BoxType = "VENTILATION"
	// Metal grid to exclude queen from honey supers
	BoxTypeQueenExcluder BoxType = "QUEEN_EXCLUDER"
	// Top-mounted syrup feeder
	BoxTypeHorizontalFeeder BoxType = "HORIZONTAL_FEEDER"
	// Bottom board/floor of hive
	BoxTypeBottom BoxType = "BOTTOM"
)

var AllBoxType = []BoxType{
	BoxTypeDeep,
	BoxTypeSuper,
	BoxTypeRoof,
	BoxTypeLargeHorizontalSection,
	BoxTypeGate,
	BoxTypeVentilation,
	BoxTypeQueenExcluder,
	BoxTypeHorizontalFeeder,
	BoxTypeBottom,
}

func (e BoxType) IsValid() bool {
	switch e {
	case BoxTypeDeep, BoxTypeSuper, BoxTypeRoof, BoxTypeLargeHorizontalSection, BoxTypeGate, BoxTypeVentilation, BoxTypeQueenExcluder, BoxTypeHorizontalFeeder, BoxTypeBottom:
		return true
	}
	return false
}

func (e BoxType) String() string {
	return string(e)
}

func (e *BoxType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BoxType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BoxType", str)
	}
	return nil
}

func (e BoxType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BoxType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BoxType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DeviceType string

const (
	DeviceTypeIotSensor   DeviceType = "IOT_SENSOR"
	DeviceTypeVideoCamera DeviceType = "VIDEO_CAMERA"
)

var AllDeviceType = []DeviceType{
	DeviceTypeIotSensor,
	DeviceTypeVideoCamera,
}

func (e DeviceType) IsValid() bool {
	switch e {
	case DeviceTypeIotSensor, DeviceTypeVideoCamera:
		return true
	}
	return false
}

func (e DeviceType) String() string {
	return string(e)
}

func (e *DeviceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeviceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeviceType", str)
	}
	return nil
}

func (e DeviceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DeviceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DeviceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Frame content types indicating what's inside the frame
type FrameType string

const (
	// Empty slot with no frame
	FrameTypeVoid FrameType = "VOID"
	// New wax foundation sheet for bees to build on
	FrameTypeFoundation FrameType = "FOUNDATION"
	// Built comb with no current contents
	FrameTypeEmptyComb FrameType = "EMPTY_COMB"
	// Divider board to reduce hive space
	FrameTypePartition FrameType = "PARTITION"
	// In-frame syrup feeder
	FrameTypeFeeder FrameType = "FEEDER"
)

var AllFrameType = []FrameType{
	FrameTypeVoid,
	FrameTypeFoundation,
	FrameTypeEmptyComb,
	FrameTypePartition,
	FrameTypeFeeder,
}

func (e FrameType) IsValid() bool {
	switch e {
	case FrameTypeVoid, FrameTypeFoundation, FrameTypeEmptyComb, FrameTypePartition, FrameTypeFeeder:
		return true
	}
	return false
}

func (e FrameType) String() string {
	return string(e)
}

func (e *FrameType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FrameType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FrameType", str)
	}
	return nil
}

func (e FrameType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FrameType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FrameType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type HiveSortBy string

const (
	HiveSortByHiveNumber     HiveSortBy = "HIVE_NUMBER"
	HiveSortByBeeCount       HiveSortBy = "BEE_COUNT"
	HiveSortByLastTreatment  HiveSortBy = "LAST_TREATMENT"
	HiveSortByLastInspection HiveSortBy = "LAST_INSPECTION"
	HiveSortByStatus         HiveSortBy = "STATUS"
	HiveSortByAdded          HiveSortBy = "ADDED"
)

var AllHiveSortBy = []HiveSortBy{
	HiveSortByHiveNumber,
	HiveSortByBeeCount,
	HiveSortByLastTreatment,
	HiveSortByLastInspection,
	HiveSortByStatus,
	HiveSortByAdded,
}

func (e HiveSortBy) IsValid() bool {
	switch e {
	case HiveSortByHiveNumber, HiveSortByBeeCount, HiveSortByLastTreatment, HiveSortByLastInspection, HiveSortByStatus, HiveSortByAdded:
		return true
	}
	return false
}

func (e HiveSortBy) String() string {
	return string(e)
}

func (e *HiveSortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HiveSortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HiveSortBy", str)
	}
	return nil
}

func (e HiveSortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HiveSortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HiveSortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Shape types for apiary obstacles
type ObstacleType string

const (
	// Circular obstacle (tree, well, etc.)
	ObstacleTypeCircle ObstacleType = "CIRCLE"
	// Rectangular obstacle (building, fence, etc.)
	ObstacleTypeRectangle ObstacleType = "RECTANGLE"
)

var AllObstacleType = []ObstacleType{
	ObstacleTypeCircle,
	ObstacleTypeRectangle,
}

func (e ObstacleType) IsValid() bool {
	switch e {
	case ObstacleTypeCircle, ObstacleTypeRectangle:
		return true
	}
	return false
}

func (e ObstacleType) String() string {
	return string(e)
}

func (e *ObstacleType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ObstacleType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ObstacleType", str)
	}
	return nil
}

func (e ObstacleType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ObstacleType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ObstacleType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortOrder string

const (
	SortOrderAsc  SortOrder = "ASC"
	SortOrderDesc SortOrder = "DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WarehouseModuleType string

const (
	WarehouseModuleTypeDeep                   WarehouseModuleType = "DEEP"
	WarehouseModuleTypeSuper                  WarehouseModuleType = "SUPER"
	WarehouseModuleTypeLargeHorizontalSection WarehouseModuleType = "LARGE_HORIZONTAL_SECTION"
	WarehouseModuleTypeRoof                   WarehouseModuleType = "ROOF"
	WarehouseModuleTypeHorizontalFeeder       WarehouseModuleType = "HORIZONTAL_FEEDER"
	WarehouseModuleTypeQueenExcluder          WarehouseModuleType = "QUEEN_EXCLUDER"
	WarehouseModuleTypeBottom                 WarehouseModuleType = "BOTTOM"
	WarehouseModuleTypeFrameFoundation        WarehouseModuleType = "FRAME_FOUNDATION"
	WarehouseModuleTypeFrameEmptyComb         WarehouseModuleType = "FRAME_EMPTY_COMB"
	WarehouseModuleTypeFramePartition         WarehouseModuleType = "FRAME_PARTITION"
	WarehouseModuleTypeFrameFeeder            WarehouseModuleType = "FRAME_FEEDER"
)

var AllWarehouseModuleType = []WarehouseModuleType{
	WarehouseModuleTypeDeep,
	WarehouseModuleTypeSuper,
	WarehouseModuleTypeLargeHorizontalSection,
	WarehouseModuleTypeRoof,
	WarehouseModuleTypeHorizontalFeeder,
	WarehouseModuleTypeQueenExcluder,
	WarehouseModuleTypeBottom,
	WarehouseModuleTypeFrameFoundation,
	WarehouseModuleTypeFrameEmptyComb,
	WarehouseModuleTypeFramePartition,
	WarehouseModuleTypeFrameFeeder,
}

func (e WarehouseModuleType) IsValid() bool {
	switch e {
	case WarehouseModuleTypeDeep, WarehouseModuleTypeSuper, WarehouseModuleTypeLargeHorizontalSection, WarehouseModuleTypeRoof, WarehouseModuleTypeHorizontalFeeder, WarehouseModuleTypeQueenExcluder, WarehouseModuleTypeBottom, WarehouseModuleTypeFrameFoundation, WarehouseModuleTypeFrameEmptyComb, WarehouseModuleTypeFramePartition, WarehouseModuleTypeFrameFeeder:
		return true
	}
	return false
}

func (e WarehouseModuleType) String() string {
	return string(e)
}

func (e *WarehouseModuleType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WarehouseModuleType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WarehouseModuleType", str)
	}
	return nil
}

func (e WarehouseModuleType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WarehouseModuleType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WarehouseModuleType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
