name: deploy
on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: pull
        working-directory: /www/swarm-api/
        run: git reset --hard && git pull

      - name: restart
        working-directory: /www/swarm-api/
        run: chmod +x restart.sh && ./restart.sh